name: audioldm_train
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - audioldm-eval==0.0.5
      - audioldm-train==0.1.0
      - audioread==3.0.1
      - backports-tarfile==1.2.0
      - braceexpand==0.1.7
      - build==1.3.0
      - cachecontrol==0.14.3
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cleo==2.1.0
      - click==8.1.7
      - contourpy==1.2.0
      - crashtest==0.4.1
      - cryptography==46.0.3
      - cycler==0.12.1
      - decorator==5.1.1
      - distlib==0.4.0
      - docker-pycreds==0.4.0
      - dulwich==0.24.10
      - einops==0.7.0
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - fastjsonschema==2.21.2
      - filelock==3.13.1
      - findpython==0.7.0
      - fonttools==4.44.0
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - ftfy==6.1.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - h11==0.16.0
      - h5py==3.10.0
      - hear21passt==0.0.23
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.17.3
      - idna==3.4
      - imageio==2.31.5
      - importlib-metadata==8.7.0
      - installer==0.7.0
      - ipdb==0.13.13
      - ipython==8.17.2
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jedi==0.19.1
      - jeepney==0.9.0
      - joblib==1.3.2
      - keyring==25.6.0
      - kiwisolver==1.4.5
      - kornia==0.7.0
      - laion-clap==1.1.7
      - lazy-loader==0.3
      - librosa==0.9.2
      - lightning-utilities==0.9.0
      - llvmlite==0.41.1
      - matplotlib==3.8.1
      - matplotlib-inline==0.1.6
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - multidict==6.0.4
      - networkx==3.2.1
      - numba==0.58.1
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - omegaconf==2.3.0
      - packaging==23.2
      - pandas==2.1.3
      - parso==0.8.3
      - pbs-installer==2025.10.31
      - pexpect==4.8.0
      - pillow==10.1.0
      - pkginfo==1.12.1.2
      - platformdirs==4.0.0
      - poetry==2.2.1
      - poetry-core==2.2.1
      - pooch==1.8.0
      - progressbar==2.5
      - prompt-toolkit==3.0.41
      - protobuf==4.25.0
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pyproject-hooks==1.2.0
      - python-dateutil==2.8.2
      - pytorch-lightning==2.1.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - rapidfuzz==3.14.3
      - regex==2023.10.3
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - resampy==0.4.2
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.0
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.9.3
      - secretstorage==3.4.0
      - sentry-sdk==1.35.0
      - setproctitle==1.3.3
      - setuptools==68.2.2
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.12.1
      - ssr-eval==0.0.7
      - stack-data==0.6.3
      - taming-transformers-rom1504==0.0.6
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - timm==0.4.12
      - tokenizers==0.13.3
      - tomli==2.0.1
      - tomlkit==0.13.3
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchlibrosa==0.0.9
      - torchmetrics==1.2.0
      - torchvision==0.14.1
      - tqdm==4.66.1
      - traitlets==5.13.0
      - transformers==4.30.2
      - trove-classifiers==2025.9.11.17
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - virtualenv==20.35.4
      - wandb==0.16.0
      - wave==0.0.2
      - wcwidth==0.2.9
      - webdataset==0.2.75
      - wget==3.2
      - wheel==0.41.3
      - yarl==1.9.2
      - zipp==3.23.0
      - zstandard==0.25.0
